src/applications/base/urls.py
from django.urls import path

from applications.base.views import HomeView, MessageView

app_name = "base"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("messages/", MessageView.as_view(), name="messages"),
]

src/apps/base/urls.py
from django.urls import path

from apps.base.views.base import HomeView, MessageView
from apps.base.views.client import ClientView
from apps.base.views.get_started import GetStartedWizard
from apps.base.views.languages import LanguagePreferencesView

app_name = "base"

urlpatterns = [
    path("", ClientView.as_view(), name="client"),
    path("previews/", ClientView.as_view(), name="client"),
    path("previews/add/<int:index>/", ClientView.as_view(), name="client"),
    path("previews/add/", ClientView.as_view(), name="client"),
    path("v2/previews/add/", ClientView.as_view(), name="client"),
    path("add/new/", ClientView.as_view(), name="client"),
    path("home/", HomeView.as_view(), name="home"),
    path("messages/", MessageView.as_view(), name="messages"),
    path("language-preferences/", LanguagePreferencesView.as_view(), name="language_preferences"),
    path("get-started/", GetStartedWizard.as_view(), name="get_started"),
]

src/apps/cards/urls.py
from django.urls import path

from apps.cards.views import CardDetailView, NextCardView

app_name = "cards"

urlpatterns = [
    path("", NextCardView.as_view(), {"action": "first"}, name="first"),
    path("any/", NextCardView.as_view(), {"action": "any"}, name="any"),
    path("next/<slug:slug>/", NextCardView.as_view(), {"action": "next"}, name="next"),
    path("previous/<slug:slug>/", NextCardView.as_view(), {"action": "previous"}, name="previous"),
    # path("", HomeView.as_view(), name="home"),
    path("<slug:slug>/", CardDetailView.as_view(), name="detail"),
]

src/apps/words/urls.py
from django.urls import path

from apps.words.views import PropertiesAPIView, WordDetailAPIView, WordListAPIView

app_name = "words"

urlpatterns = [
    path("", WordListAPIView.as_view(), name="list"),
    path("<int:id>/", WordDetailAPIView.as_view(), name="detail"),
    path("properties/", PropertiesAPIView.as_view(), name="properties"),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from allauth.account.views import confirm_email

from core.views import schema_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    re_path('auth/registration/account-confirm-email/(?P<key>.+)/', confirm_email, name='account_confirm_email'),
    path("auth/", include("dj_rest_auth.urls")),
    path("auth/registration/", include("dj_rest_auth.registration.urls")),

    path("", include("apps.base.urls", namespace="base")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("cards/", include("apps.cards.urls", namespace="cards")),
]

oas_urls = [
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    # To serve static files in debug mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # To serve media files in debug mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # To serve OpenAPI Specification
    urlpatterns += oas_urls

src/apps/base/forms.py
from django import forms
from django.utils.translation import gettext as _

from apps.base.constants import PRIMARY_LANGUAGE, SECONDARY_LANGUAGE
from apps.base.utils.languages import get_language_choices, get_level_choices


class LanguagePreferencesForm(forms.Form):
    language_choices = get_language_choices()
    primary_language = forms.ChoiceField(
        choices=language_choices.get(PRIMARY_LANGUAGE, None), label=_("Language to learn")
    )
    secondary_language = forms.ChoiceField(
        choices=language_choices.get(SECONDARY_LANGUAGE, None), label=_("Secondary language")
    )
    level = forms.ChoiceField(choices=get_level_choices(), label=_("Difficulty Level"))

src/apps/base/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "base/welcome.html"


class MessageView(TemplateView):
    template_name = "base/message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.GET.get("title", "You Got the Following Messages")
        return context

src/apps/base/views/base.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "base/welcome.html"


class MessageView(TemplateView):
    template_name = "base/message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.GET.get("title", "You Got the Following Messages")
        return context

src/apps/base/views/client.py
from django.views.generic import TemplateView


class ClientView(TemplateView):
    template_name = "index.html"

src/apps/base/views/get_started.py
from django import forms
from django.shortcuts import render
from django.utils.translation import gettext as _
from formtools.wizard.views import SessionWizardView

from apps.base.constants import IS_LANGUAGES_SELECTED, PRIMARY_LANGUAGE, SECONDARY_LANGUAGE
from apps.base.utils.decorators import form_helper
from apps.base.utils.languages import get_language_choices, get_level_choices, set_language_preferences


@form_helper
class PageOneForm(forms.Form):
    primary_language = forms.ChoiceField(
        choices=get_language_choices().get(PRIMARY_LANGUAGE, None),
        label=_("Language to learn"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageTwoForm(forms.Form):
    secondary_language = forms.ChoiceField(
        choices=get_language_choices().get(SECONDARY_LANGUAGE, None),
        label=_("Secondary language"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageThreeForm(forms.Form):
    level = forms.ChoiceField(
        choices=get_level_choices(),
        label=_("Difficulty Level"),
        widget=forms.RadioSelect(),
    )


class GetStartedWizard(SessionWizardView):
    form_list = [PageOneForm, PageTwoForm, PageThreeForm]
    template_name = "base/get-started.html"

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        all_data = {}
        for step in self.get_form_list():
            cleaned_data = self.get_cleaned_data_for_step(step) or {}
            all_data.update(cleaned_data)
        context["all_data"] = all_data
        return context

    def done(self, form_list, **kwargs):
        data = {}
        for form in form_list:
            data.update(form.cleaned_data)

        response = render(self.request, "base/welcome.html", {IS_LANGUAGES_SELECTED: True})
        set_language_preferences(response=response, data=data)

        return response

src/apps/base/views/languages.py
from django.shortcuts import render
from django.views import View

from apps.base.constants import IS_LANGUAGES_SELECTED
from apps.base.forms import LanguagePreferencesForm
from apps.base.utils.languages import get_language_preferences, set_language_preferences


class LanguagePreferencesView(View):
    template_name = "base/components/update.html"
    form_class = LanguagePreferencesForm

    def get(self, request, *args, **kwargs):
        initial_data = get_language_preferences(request=request)
        form = self.form_class(initial=initial_data)
        context = {
            "form": form,
            "action_url_name": "base:language_preferences",
            "title": "Language Preferences",
            "button_color": "btn-success",
            "button_text": "Submit",
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            context = {IS_LANGUAGES_SELECTED: True}
            response = render(request, "base/welcome.html", context)
            cleaned_data = form.cleaned_data
            set_language_preferences(response=response, data=cleaned_data)
            return response

src/apps/base/views/mpview.py
from django import forms
from django.shortcuts import render
from django.utils.translation import gettext as _
from formtools.wizard.views import SessionWizardView

from apps.base.constants import PRIMARY_LANGUAGE, SELECTED_LANGUAGE
from apps.base.utils.decorators import form_helper
from apps.base.utils.languages import get_language_choices, get_level_choices


@form_helper
class PageOneForm(forms.Form):
    selected_language = forms.ChoiceField(
        choices=get_language_choices().get(SELECTED_LANGUAGE, None),
        label=_("Language to learn"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageTwoForm(forms.Form):
    primary_language = forms.ChoiceField(
        choices=get_language_choices().get(PRIMARY_LANGUAGE, None),
        label=_("Secondary language"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageThreeForm(forms.Form):
    level = forms.ChoiceField(
        choices=get_level_choices(),
        label=_("Difficulty Level"),
        widget=forms.RadioSelect(),
    )


class MyFormWizard(SessionWizardView):
    form_list = [PageOneForm, PageTwoForm, PageThreeForm]
    template_name = "base/preferences.html"

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        all_data = {}
        for step in self.get_form_list():
            cleaned_data = self.get_cleaned_data_for_step(step) or {}
            all_data.update(cleaned_data)
        context["all_data"] = all_data
        return context

    def done(self, form_list, **kwargs):
        data = {}
        for form in form_list:
            data.update(form.cleaned_data)

        response = render(self.request, "base/welcome.html", {"form_data": data})
        for key, value in data.items():
            response.set_cookie(key, value)

        return response

src/apps/base/templates/base/get-started.html
{% extends "base.html" %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block main_content %}
  
  <div class="container text-center">
    <div class="container d-flex justify-content-center pt-4 pb-4">
      <div class="card shadow profile pt-4 pb-2">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <form method="post">
                {% csrf_token %}
                {{ wizard.management_form }}
                {% for field in form %}
                  {% if field.field.widget.input_type == 'radio' %}
                    <h5 class="card-title text-center">{{ field.label }}</h5>
                    {% for choice in field %}
                      <div class="p-2">
                        <div class="card" style="cursor: pointer; min-height: 6rem;" onclick="selectRadio(this, '{{ choice.id_for_label }}')">
                          <div class="card-body d-flex flex-column justify-content-center">
                            <h5 class="card-title">
                              <label class="form-check-label">
                              {{ choice.tag }}
                              {{ choice.choice_label }}
                              </label>
                            </h5>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              
                <div class="d-flex btn-group p-2">
                  <button type="submit" class="btn btn-success">
                    {% if wizard.steps.current == wizard.steps.last %}Submit{% else %}Next{% endif %}
                  </button>
                </div>
              </form>
            
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <script>
    function selectRadio(card, radioId) {
      const selectStyles = ['selected', 'bg-primary', 'text-light'];
      
      // Remove the 'selected' class from all cards
      const cards = document.querySelectorAll('.card');
      cards.forEach(item => item.classList.remove(...selectStyles));

      // Add the 'selected' class to the clicked card
      card.classList.add(...selectStyles);

      // Check the corresponding radio input
      document.getElementById(radioId).checked = true;
    }
  </script>

  <style>
    /* Hide radio buttons */
    input[type="radio"] {
      display: none;
    }
    
    .selected {
      transition: 0.5s;
    }
  </style>

{% endblock main_content %}

src/apps/base/templates/base/message.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block head_title %}{% blocktrans %}{{ title }}{% endblocktrans %}{% endblock head_title %}

{% block main_content %}
  <div class="text-center m-2">
    <div class="display-5">{% blocktrans %}{{ title }}{% endblocktrans %}</div>
    {% if messages %}
      <div>
        {% for message in messages %}
          <div class="display-6">{% blocktrans %}{{ message }}{% endblocktrans %}</div>
        {% endfor %}
      </div>
    {% else %}
      {% url 'base:home' as home_url %}
      <script>
        window.location.href = "{% if home_url %}{{ home_url }}{% else %}/{% endif %}";
      </script>
    {% endif %}
  </div>
{% endblock main_content %}

src/apps/base/templates/base/messages.html
{% if messages %}
  <div>
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

src/apps/base/templates/base/preferences.html
{% extends "base.html" %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block main_content %}
  
  <div class="container text-center">
    <div class="container d-flex justify-content-center pt-4 pb-4">
      <div class="card shadow profile pt-4 pb-2">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <form method="post">
                {% csrf_token %}
                {{ wizard.management_form }}
                {% for field in form %}
                  {% if field.field.widget.input_type == 'radio' %}
                    <h5 class="card-title text-center">{{ field.label }}</h5>
                    {% for choice in field %}
                      <div class="p-2">
                        <div class="card" style="cursor: pointer; min-height: 6rem;" onclick="selectRadio(this, '{{ choice.id_for_label }}')">
                          <div class="card-body d-flex flex-column justify-content-center">
                            <h5 class="card-title">
                              <label class="form-check-label">
                              {{ choice.tag }}
                              {{ choice.choice_label }}
                              </label>
                            </h5>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              
                <div class="d-flex btn-group p-2">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <script>
    function selectRadio(card, radioId) {
      const selectStyles = ['selected', 'bg-primary', 'text-light'];
      
      // Remove the 'selected' class from all cards
      const cards = document.querySelectorAll('.card');
      cards.forEach(item => item.classList.remove(...selectStyles));

      // Add the 'selected' class to the clicked card
      card.classList.add(...selectStyles);

      // Check the corresponding radio input
      document.getElementById(radioId).checked = true;
    }
  </script>

  <style>
    /* Hide radio buttons */
    input[type="radio"] {
      display: none;
    }
    
    .selected {
      transition: 0.5s;
    }
  </style>

{% endblock main_content %}

src/apps/base/templates/base/welcome.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block head_title %}{% trans "German Vocabulary" %}{% endblock head_title %}

{% block main_content %}
  <div class="text-center m-2">
    <img class="pb-4 img-fluid rotate-continuously" src="{% static 'base/images/favicon/android-chrome-512x512.png' %}"
         alt="brand-logo" width="100">
    <div class="display-5">{% blocktrans %}Welcome to {{ brand_name }}{% endblocktrans %}</div>
    {% if is_languages_selected %}
      <div class="display-6 pt-2">{% trans "Keep Learning" %}</div>
      <div class="pt-4">
        <a href="{% url 'cards:first' %}">
          <button class="btn btn-outline-secondary me-2" type="button">{% trans "Flashcard" %}</button>
        </a>
        <a href="{% url 'words:list' %}">
          <button class="btn btn-outline-secondary" type="button">{% trans "Words" %}</button>
        </a>
      </div>
    {% else %}
      <div class="display-6">{% trans "Select an option to Continue" %}</div>
      <div class="pt-4">
        <a href="{% url 'base:get_started' %}">
          <button class="btn btn-outline-success me-2" type="button">{% trans "Get Started" %}</button>
        </a>
      </div>
    {% endif %}
    {% if not request.user.is_authenticated %}
      <div class="pt-2">
        <a href="{% url 'account_signup' %}">
          <button class="btn btn-outline-dark me-2" type="button">{% trans "Sign Up" %}</button>
        </a>
        <a href="{% url 'account_login' %}">
          <button class="btn btn-outline-secondary" type="button">{% trans "Log In" %}</button>
        </a>
      </div>
    {% endif %}
  </div>
{% endblock main_content %}