src/apps/words/urls.py
from django.urls import path

from apps.words.views import PropertiesAPIView, WordDetailAPIView, WordListAPIView

app_name = "words"

urlpatterns = [
    path("", WordListAPIView.as_view(), name="list"),
    path("<int:id>/", WordDetailAPIView.as_view(), name="detail"),
    path("properties/", PropertiesAPIView.as_view(), name="properties"),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from allauth.account.views import confirm_email

from core.views import schema_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    re_path('auth/registration/account-confirm-email/(?P<key>.+)/', confirm_email, name='account_confirm_email'),
    path("auth/", include("dj_rest_auth.urls")),
    path("auth/registration/", include("dj_rest_auth.registration.urls")),

    path("", include("apps.base.urls", namespace="base")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("cards/", include("apps.cards.urls", namespace="cards")),
]

oas_urls = [
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    # To serve static files in debug mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # To serve media files in debug mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # To serve OpenAPI Specification
    urlpatterns += oas_urls

src/apps/words/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.base.utils.decorators import auto_slugify
from apps.base.utils.images import resize_image
from apps.base.utils.validators import validate_alphanumeric, validate_file_size
from apps.users.constants import DEFAULT_WORD_IMAGE
from apps.words.utils import getLevelChoices


class Image(models.Model):
    title = models.CharField(max_length=100, unique=True, validators=[validate_alphanumeric])
    image = models.ImageField(default=DEFAULT_WORD_IMAGE, upload_to="words/", validators=[validate_file_size])
    description = models.TextField(default="", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        resize_image(instance=self, field_name="image", title=self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.image.url.split("/media/", maxsplit=1)[1])  # The part after '/media/'


@auto_slugify(field_name="title")
class Article(models.Model):
    slug = models.SlugField(editable=False)
    title = models.CharField(max_length=5, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class PartOfSpeech(models.Model):
    title = models.CharField(max_length=20, unique=True)
    bundle = models.ForeignKey("Bundle", on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Part of Speech"
        verbose_name_plural = "Parts of Speech"
        unique_together = ("title", "bundle")

    def __str__(self):
        return self.title


class Language(models.Model):
    """
    During adding a language, it shows all the available languages from settings where the list of languages are saved
    in a pair of (code, name) i.e. ('en', 'English').

    A dictionary is created from this list of tuple to return the corresponding name during string representation of the
    object specially helpful in the list of this model in the admin panel.

    The 'slug' field is not editable and is read only in detail view in the admin panel only during the update view.
    """

    languages, code_choices = dict(), list()
    for pt1, name in settings.LANGUAGES:
        language = (pt1, _(name))
        code_choices.append(language)
        languages.update([language])

    code = models.CharField(unique=True, max_length=7, choices=code_choices)
    title = models.CharField(max_length=100, editable=False)
    articles = models.ManyToManyField(Article, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        self.title = dict(self.languages).get(self.code, self.code)
        super().save(*args, **kwargs)


class Note(models.Model):
    title = models.TextField(default="", blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        size, max_size = len(self.title), 100
        return f"{self.title if size <= max_size else self.title[:max_size]+'...'}"


@auto_slugify(field_name="title")
class Word(models.Model):
    slug = models.SlugField(editable=False)
    title = models.CharField(max_length=100)
    plural = models.CharField(max_length=100, blank=True, null=True)
    linked_words = models.ManyToManyField("self", blank=True, symmetrical=True, verbose_name="Linked Words")
    translations = models.ManyToManyField("self", blank=True, symmetrical=False)
    description = models.TextField(default="", blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)
    articles = models.ManyToManyField(Article, blank=True)
    part_of_speech = models.ForeignKey(
        PartOfSpeech, on_delete=models.SET_NULL, null=True, verbose_name="Part of Speech"
    )
    sentence = models.TextField(default="", blank=True, null=True)
    level = models.CharField(max_length=2, choices=getLevelChoices())
    notes = models.ManyToManyField(Note, blank=True)
    hidden = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ["title", "language", "part_of_speech"]

    def __str__(self):
        return f"{self.title} | {self.language}"


@auto_slugify(field_name="title")
class Bundle(models.Model):
    slug = models.SlugField(editable=False)
    title = models.CharField(max_length=100)
    description = models.TextField(default="", blank=True, null=True)
    image = models.ManyToManyField(Image, blank=True)
    words = models.ManyToManyField(Word, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

src/apps/words/models/vocabulary.py
from django.db import models
from apps.base.utils.decorators import auto_generate_slug

from apps.words.models.image import Image
from apps.words.models.article import Article
from apps.words.models.language import Language


@auto_generate_slug(field_name="word")
class Vocabulary(models.Model):
    slug = models.SlugField(editable=False)
    word = models.CharField(max_length=100)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    articles = models.ManyToManyField(Article, blank=True)
    image = models.ManyToManyField(Image, blank=True)

    class Meta:
        verbose_name_plural = "Vocabulary"
        unique_together = ["word", "language"]

    def __str__(self):
        return f"{self.word} | {self.language}"

src/apps/words/forms.py
from django import forms
from django.db.models.functions import Lower

from apps.base.utils.decorators import filter_data_by_field
from apps.base.utils.validators import validate_field_unchanged
from apps.words.models import Article, Language, Word


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = "__all__"

    @validate_field_unchanged(model=Language, field_name="code")
    def clean_code(self):
        return self.cleaned_data["code"]


class WordForm(forms.ModelForm):
    class Meta:
        model = Word
        fields = "__all__"

    @filter_data_by_field(
        destination_class=Article,
        destination_field_name="articles",
        source_class=Language,
        source_field_name="language",
        dependency_field_name="articles",
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get("instance")
        if instance:
            language = instance.language
            part_of_speech = instance.part_of_speech
            self.fields["linked_words"].queryset = (
                Word.objects.filter(language=language, part_of_speech=part_of_speech)
                .exclude(pk=instance.pk)
                .order_by("-modified", "language__code", Lower("title"))
                .distinct()
            )

            self.fields["translations"].queryset = (
                Word.objects.filter(part_of_speech=part_of_speech)
                .exclude(language=language)
                .order_by("-modified", "language__code", Lower("title"))
                .distinct()
            )

src/apps/words/views.py
from drf_yasg.utils import swagger_auto_schema
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.response import Response

from apps.api.utils import serializer_to_manual_parameters
from apps.words.constants import LEVELS
from apps.words.models import Language, PartOfSpeech, Word
from apps.words.serializers import (
    LanguageSerializer,
    PartOfSpeechSerializer,
    WordListQueryParamsSerializer,
    WordListSerializer,
    WordSerializer,
)


class BaseWordListAPIView(ListAPIView):
    model = None
    serializer_class = None
    query_params_serializer_class = None

    def get_queryset(self):
        params_serializer = self.query_params_serializer_class(data=self.request.query_params)
        params_serializer.is_valid(raise_exception=True)

        primary_language = params_serializer.validated_data.get("primary_language", "de")
        level = params_serializer.validated_data.get("level", None)
        search_query = params_serializer.validated_data.get("q", "")

        queryset = self.model.objects.filter(language__code=primary_language)

        if level is not None:
            queryset = queryset.filter(level=level)

        if hasattr(self.model, "hidden"):
            queryset = queryset.filter(hidden=False)
        if hasattr(self.model, "in_review"):
            queryset = queryset.filter(in_review=False)
        if hasattr(self.model, "merged"):
            queryset = queryset.filter(merged=False)

        if search_query:
            queryset = queryset.filter(title__icontains=search_query)

        return queryset


class WordListAPIView(BaseWordListAPIView):
    model = Word
    serializer_class = WordListSerializer
    query_params_serializer_class = WordListQueryParamsSerializer

    @swagger_auto_schema(manual_parameters=serializer_to_manual_parameters(query_params_serializer_class))
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class WordDetailAPIView(RetrieveAPIView):
    serializer_class = WordSerializer
    queryset = Word.objects.all()
    lookup_field = "id"


class PropertiesAPIView(ListAPIView):
    serializer_class = LanguageSerializer

    def get_queryset(self):
        # Assuming you want to return Language objects
        return Language.objects.all().order_by("modified")

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        languages_serializer = self.get_serializer(queryset, many=True)

        parts_of_speech = PartOfSpeech.objects.all()
        parts_of_speech_serializer = PartOfSpeechSerializer(parts_of_speech, many=True)

        data = {
            "languages": languages_serializer.data,
            "parts_of_speech": parts_of_speech_serializer.data,
            "levels": LEVELS,
        }
        return Response(data)

src/apps/words/templates/words/detail.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block head_title %}{% trans "Words" %}{% endblock head_title %}

{% block main_content %}
  <div class="container d-flex justify-content-center text-center pt-5 pb-4">
    <a href="{% url 'cards:detail' slug=object.pk %}">
      <div class="card word text-bg-light mb-3" style="min-width: 16rem; max-width: 20rem; min-height: 10rem;">
        <div class="card-header inline-content" style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
          {% if object.articles.all %}
            <div style="text-align: left;">
              {% for article in object.articles.all %}
                <span class="badge bg-primary rounded-pill">{{ article }}</span>
                <!-- {% if not forloop.last %}&nbsp;{% endif %} -->
              {% endfor %}
            </div>
          {% endif %}
          <div style="text-align: center;">
            {% for part_of_speech in object.parts_of_speech.all %}
              {% for word in part_of_speech.bundle.words.all %}
                {% if word.language.code == "en" %}
                  <span class="badge bg-success rounded-pill">{{ word.title }}</span>
                {% endif %}
              {% endfor %}
            {% endfor %}
          </div>
          <div style="text-align: right;">
            <span class="badge bg-dark rounded-pill">{{ object.level|upper }}</span>
          </div>
        </div>
        <div class="card-body text-center">
          <h5 class="card-title text-dark">
            {{ object.title }}
          </h5>
          <p class="card-text text-dark">
            {{ object.sentence }}
          </p>
          <p class="card-text text-dark" style="text-align: justify;">
            {{ object.description }}
          </p>
        </div>
      </div>
    </a>
  </div>
{% endblock main_content %}

src/apps/words/templates/words/list.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block head_title %}{% trans "Words" %}{% endblock head_title %}

{% block main_content %}
  <div class="container pt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="centered-form ps-5 pe-5">
          <form method="GET" class="form-inline search-bar" id="search_bar">
            <div class="input-group">
              <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
              <label for="search_input" class="sr-only">Search:</label>
              <input type="text" id="search_input" name="q" placeholder="Search..." value="{{ request.GET.q }}" class="form-control">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center pt-5 ps-4 pe-4">
    {% for object in object_list %}
      <div class="col-lg-3 col-md-4 col-sm-6 col-6 mb-3">
        <a href="{% url 'cards:detail' slug=object.pk %}">
          <div class="card word text-bg-light mb-3" style="max-width: 18rem; min-height: 10rem;">
            <div class="card-header inline-content" style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
              {% if object.articles.all %}
                <div style="text-align: left;">
                  {% for article in object.articles.all %}
                    <span class="badge bg-primary rounded-pill">{{ article }}</span>
                    <!-- {% if not forloop.last %}&nbsp;{% endif %} -->
                  {% endfor %}
                </div>
              {% endif %}
              <div style="text-align: center;">
                {% for part_of_speech in object.parts_of_speech.all %}
                  {% for word in part_of_speech.bundle.words.all %}
                    {% if word.language.code == "en" %}
                      <span class="badge bg-success rounded-pill">{{ word.title }}</span>
                    {% endif %}
                  {% endfor %}
                {% endfor %}
              </div>
              <div style="text-align: right;">
                <span class="badge bg-dark rounded-pill">{{ object.level|upper }}</span>
              </div>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title text-dark">
                {{ object.title }}
              </h5>
              <p class="card-text text-dark">
                {{ object.sentence }}
              </p>
            </div>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
  <div class="container d-flex justify-content-center pt-4 pagination-container">
    {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination search-bar">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true"><i class="fa-solid fa-backward-step"></i></a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-angle-left"></i></a>
            </li>
          {% else %}
            <li class="page-item disabled" aria-disabled="true">
              <span class="page-link"><i class="fa-solid fa-backward-step"></i></span>
            </li>
            <li class="page-item disabled" aria-disabled="true">
              <span class="page-link"><i class="fa-solid fa-angle-left"></i></span>
            </li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if num >= page_obj.number|add:"-3" and num <= page_obj.number|add:"3" %}
              {% if num == page_obj.number %}
                <li class="page-item active" aria-current="page">
                  <span class="page-link">{{ num }}</span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
              {% endif %}
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-angle-right"></i></a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ paginator.num_pages }}"><i class="fa-solid fa-forward-step"></i></a>
            </li>
          {% else %}
            <li class="page-item disabled" aria-disabled="true">
              <span class="page-link"><i class="fa-solid fa-angle-right"></i></span>
            </li>
            <li class="page-item disabled" aria-disabled="true">
              <span class="page-link"><i class="fa-solid fa-forward-step"></i></span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>

  <script src="{% static 'words/scripts/base.js' %}"></script>
{% endblock main_content %}