src/apps/cards/urls.py
from django.urls import path

from apps.cards.views import CardDetailView, NextCardView

app_name = "cards"

urlpatterns = [
    path("", NextCardView.as_view(), {"action": "first"}, name="first"),
    path("any/", NextCardView.as_view(), {"action": "any"}, name="any"),
    path("next/<slug:slug>/", NextCardView.as_view(), {"action": "next"}, name="next"),
    path("previous/<slug:slug>/", NextCardView.as_view(), {"action": "previous"}, name="previous"),
    # path("", HomeView.as_view(), name="home"),
    path("<slug:slug>/", CardDetailView.as_view(), name="detail"),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from allauth.account.views import confirm_email

from core.views import schema_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    re_path('auth/registration/account-confirm-email/(?P<key>.+)/', confirm_email, name='account_confirm_email'),
    path("auth/", include("dj_rest_auth.urls")),
    path("auth/registration/", include("dj_rest_auth.registration.urls")),

    path("", include("apps.base.urls", namespace="base")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("cards/", include("apps.cards.urls", namespace="cards")),
]

oas_urls = [
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    # To serve static files in debug mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # To serve media files in debug mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # To serve OpenAPI Specification
    urlpatterns += oas_urls

src/kernel/urls.py
from django.urls import path

from kernel.views import HomeView

app_name = "kernel"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

src/apps/cards/views.py
from django.contrib import messages
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import DetailView, TemplateView

from apps.base.utils.decorators import language_preferences_required
from apps.base.utils.languages import get_level, get_primary_language, get_secondary_language
from apps.words.models import Bundle, Word


class HomeView(TemplateView):
    template_name = "cards/index.html"


class CardDetailView(DetailView):
    template_name = "cards/detail.html"
    model = Word
    context_object_name = "object"

    def get_object(self, queryset=None):
        pk = self.kwargs["slug"]
        primary_word = Word.objects.get(pk=pk)
        secondary_language = get_secondary_language(request=self.request)
        secondary_word = primary_word.translations.filter(language__code=secondary_language).first()
        return {"primary_word": primary_word, "secondary_word": secondary_word if secondary_word else primary_word}

    @language_preferences_required
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class NextCardView(View):
    @staticmethod
    def get_next_word(request, action, current_word, language, level):
        next_word = None
        if action == "first":
            next_word = Word.objects.filter(language__code=language, hidden=False).order_by(Lower("title")).first()
        elif action == "any":
            next_word = Word.objects.filter(language__code=language, level=level, hidden=False).order_by("?").first()
        elif action == "next":
            next_word = (
                Word.objects.filter(language__code=language, level=level, hidden=False)
                .annotate(lower_title=Lower("title"))
                .filter(lower_title__gt=current_word.title.lower())
                .order_by("lower_title")
                .first()
            )
            if not next_word:
                messages.warning(request, _("This is the last word in this section."))
        elif action == "previous":
            next_word = (
                Word.objects.filter(language__code=language, level=level, hidden=False)
                .annotate(lower_title=Lower("title"))
                .filter(lower_title__lt=current_word.title.lower())
                .order_by("lower_title")
                .first()
            )
            if not next_word:
                messages.warning(request, _("This is the first word in this section."))
        return next_word

    def get(self, request, action="next", slug=None):
        language = get_primary_language(request=request)
        level = get_level(request=request)
        current_word = get_object_or_404(Word, pk=slug) if slug else None
        next_word = self.get_next_word(
            request=request, action=action, current_word=current_word, language=language, level=level
        )

        if next_word:
            slug = next_word.pk

        # Redirect to home if no data in the table for this model.
        # TODO: Redirect to a not found page if no word found with this language preference.
        return redirect("cards:detail", slug=slug) if slug else redirect("base:home")

src/apps/cards/templates/cards/detail.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block head_title %}{% trans "Flashcards" %}{% endblock head_title %}

{% block main_content %}
  <div class="container d-flex justify-content-center" >
    {% include 'cards/messages.html' %}
  </div>
  <div class="container d-flex justify-content-center text-center">
    <div class="cardContainer card-text-color fade-in-container text-shadow pt-4 ps-2 pe-2">
      <div class="flashcard" id="flashCard">
        <div class="front">
          <div>
            {% if object.primary_word.linked_words.all %}
              <!-- part_of_speech -->
              {% for part_of_speech in object.primary_word.parts_of_speech.all %}
                {% for word in part_of_speech.bundle.words.all %}
                  {% if word.language.code == "en" %}
                    <span class="badge bg-primary rounded-pill" style="font-size: 1rem;">{{ word.title }}</span>
                  {% endif %}
                {% endfor %}
              {% endfor %}
            {% endif %}
            <div class="display-3 shadows-into-light-regular" style="font-size: 4rem;">{{ object.primary_word.title }}</div>
          </div>
          {% if object.primary_word.linked_words.all %}
            <div class="ms-2 me-2 mt-5" style="font-size: 1.2rem;">
              <span class="badge bg-secondary rounded-pill card-text-color">
                <i class="fa-solid fa-link me-1"></i>{% trans "Linked" %}
              </span>
            </div>
            <div id="linkedWords">
              {% for word in object.primary_word.linked_words.all %}
                <!-- part_of_speech -->
                {% for part_of_speech in word.parts_of_speech.all %}
                  {% for word in part_of_speech.bundle.words.all %}
                    {% if word.language.code == "en" %}
                      <span class="badge bg-success rounded-pill" style="font-size: 1rem;">{{ word.title }}</span>
                    {% endif %}
                  {% endfor %}
                {% endfor %}
                <div>
                  <a href="{% url 'cards:detail' slug=word.pk %}" class="style-script-regular linked-word card-text-color ms-2 me-2" onclick="preventCardRotation(event)">{{ word.title }}</a>
                </div>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        <div class="back">
          <div style="font-size: 1.5rem;">
            <!-- article -->
            {% for article in object.primary_word.articles.all %}
              <span class="badge bg-primary rounded-pill">{{ article }}</span>
              <!-- {% if not forloop.last %}&nbsp;{% endif %} -->
            {% endfor %}

            <!-- part_of_speech -->
            {% for part_of_speech in object.primary_word.parts_of_speech.all %}
              {% for word in part_of_speech.bundle.words.all %}
                {% if word.language.code == "en" %}
                  <span class="badge bg-secondary rounded-pill">{{ word.title }}</span>
                {% endif %}
              {% endfor %}
            {% endfor %}
          </div>

          <div class="display-5 shadows-into-light-regular">{{ object.primary_word.title }}</div>
          <div class="ms-2 me-2" style="font-size: 1.5rem;">{{ object.primary_word.sentence }}</div>
          <i class="fa-regular fa-circle-play" id="playButton" onclick="playText('{% url 'speech:tts' %}', '{{ object.primary_word.sentence }}', '{{ object.primary_word.language.code }}')"
               style="font-size: 2.5rem;"></i>

          <div class="dotted-line"></div>

          <div class="display-5 shadows-into-light-regular">{{ object.secondary_word.title }}</div>
          <div class="ms-2 me-2" style="font-size: 1.5rem;">{{ object.secondary_word.sentence }}</div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="text-center pt-3">
      <a href="{% url 'cards:previous' slug=object.primary_word.pk %}" class="cardButton me-2"><i class="fa-solid fa-circle-left"></i></a>
      <a href="{% url 'cards:any' %}" class="cardButton me-2"><i class="fa-solid fa-rotate"></i></a>
      <a href="{% url 'cards:next' slug=object.primary_word.pk %}" class="cardButton"><i class="fa-solid fa-circle-right"></i></a>
    </div>
  </div>
  <audio id="flipAudio" src="{% static 'cards/audio/flip_card.mp3' %}"></audio>

  <script src="{% static 'cards/scripts/base.js' %}"></script>
  <script src="{% static 'cards/scripts/loadCard.js' %}"></script>
  <script src="{% static 'cards/scripts/tts.js' %}"></script>
  <script src="{% static 'cards/scripts/ttsAPI.js' %}"></script>
  <script src="{% static 'cards/scripts/messages.js' %}"></script>
{% endblock main_content %}

src/apps/cards/templates/cards/index.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block head_title %}{% trans "Flashcards" %}{% endblock head_title %}

{% block main_content %}
  <div class="container d-flex justify-content-center">
    <div class="cardContainer fade-in-container pt-3">
      <div class="flashcard" id="flashCard">
        <div class="front">
          <h2>Buch</h2>
        </div>
        <div class="back">
          <h2>das Buch</h2>
          <h3>Book</h3>
          <p>Das ist mein Buch.</p>
          <p>This is my book.</p>
          <i class="fa-regular fa-circle-play" id="playButton" onclick="playText('Das ist mein Buch.', 'de-DE')"
             style="font-size: 3em;"></i>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="text-center pt-3">
      <a href="{% url 'cards:home' %}" class="cardButton me-2"><i class="fa-solid fa-circle-left"></i></a>
      <a href="{% url 'cards:home' %}" class="cardButton"><i class="fa-solid fa-circle-right"></i></a>
    </div>
  </div>
  <audio id="flipAudio" src="{% static 'cards/audio/flip_card.mp3' %}"></audio>

  <script src="{% static 'cards/scripts/base.js' %}"></script>
  <script src="{% static 'cards/scripts/loadCard.js' %}"></script>
  <script src="{% static 'cards/scripts/tts.js' %}"></script>
{% endblock main_content %}

src/apps/cards/templates/cards/messages.html
{% if messages %}
  <div>
    {% for message in messages %}
    <div class="modal text-secondary" id="autoCloseModal" tabindex="-1" aria-labelledby="autoCloseModalLabel" aria-hidden="true">
      <div class="modal-dialog pt-4">
        <div class="modal-content pt-md-5 pt-3">
          <div class="modal-body">
            <div id="message-content">
              {{ message }}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endif %}