src/applications/base/urls.py
from django.urls import path

from applications.base.views import HomeView, MessageView

app_name = "base"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("messages/", MessageView.as_view(), name="messages"),
]

src/apps/base/urls.py
from django.urls import path

from apps.base.views.base import HomeView, MessageView
from apps.base.views.client import ClientView
from apps.base.views.get_started import GetStartedWizard
from apps.base.views.languages import LanguagePreferencesView

app_name = "base"

urlpatterns = [
    path("", ClientView.as_view(), name="client"),
    path("previews/", ClientView.as_view(), name="client"),
    path("previews/add/<int:index>/", ClientView.as_view(), name="client"),
    path("previews/add/", ClientView.as_view(), name="client"),
    path("v2/previews/add/", ClientView.as_view(), name="client"),
    path("add/new/", ClientView.as_view(), name="client"),
    path("home/", HomeView.as_view(), name="home"),
    path("messages/", MessageView.as_view(), name="messages"),
    path("language-preferences/", LanguagePreferencesView.as_view(), name="language_preferences"),
    path("get-started/", GetStartedWizard.as_view(), name="get_started"),
]

src/apps/cards/urls.py
from django.urls import path

from apps.cards.views import CardDetailView, NextCardView

app_name = "cards"

urlpatterns = [
    path("", NextCardView.as_view(), {"action": "first"}, name="first"),
    path("any/", NextCardView.as_view(), {"action": "any"}, name="any"),
    path("next/<slug:slug>/", NextCardView.as_view(), {"action": "next"}, name="next"),
    path("previous/<slug:slug>/", NextCardView.as_view(), {"action": "previous"}, name="previous"),
    # path("", HomeView.as_view(), name="home"),
    path("<slug:slug>/", CardDetailView.as_view(), name="detail"),
]

src/apps/users/urls.py
from django.urls import path

from apps.users.views import ProfileUpdateView, ProfileView

app_name = "users"

urlpatterns = [
    path("<slug:slug>", ProfileView.as_view(), name="profile"),
    path("update/<slug:slug>", ProfileUpdateView.as_view(), name="profile_update"),
]

src/apps/words/urls.py
from django.urls import path

from apps.words.views import PropertiesAPIView, WordDetailAPIView, WordListAPIView

app_name = "words"

urlpatterns = [
    path("", WordListAPIView.as_view(), name="list"),
    path("<int:id>/", WordDetailAPIView.as_view(), name="detail"),
    path("properties/", PropertiesAPIView.as_view(), name="properties"),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from allauth.account.views import confirm_email

from core.views import schema_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    re_path('auth/registration/account-confirm-email/(?P<key>.+)/', confirm_email, name='account_confirm_email'),
    path("auth/", include("dj_rest_auth.urls")),
    path("auth/registration/", include("dj_rest_auth.registration.urls")),

    path("", include("apps.base.urls", namespace="base")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("cards/", include("apps.cards.urls", namespace="cards")),
]

oas_urls = [
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    # To serve static files in debug mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # To serve media files in debug mode
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # To serve OpenAPI Specification
    urlpatterns += oas_urls

src/apps/base/forms.py
from django import forms
from django.utils.translation import gettext as _

from apps.base.constants import PRIMARY_LANGUAGE, SECONDARY_LANGUAGE
from apps.base.utils.languages import get_language_choices, get_level_choices


class LanguagePreferencesForm(forms.Form):
    language_choices = get_language_choices()
    primary_language = forms.ChoiceField(
        choices=language_choices.get(PRIMARY_LANGUAGE, None), label=_("Language to learn")
    )
    secondary_language = forms.ChoiceField(
        choices=language_choices.get(SECONDARY_LANGUAGE, None), label=_("Secondary language")
    )
    level = forms.ChoiceField(choices=get_level_choices(), label=_("Difficulty Level"))

src/apps/base/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "base/welcome.html"


class MessageView(TemplateView):
    template_name = "base/message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.GET.get("title", "You Got the Following Messages")
        return context

src/apps/base/views/base.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "base/welcome.html"


class MessageView(TemplateView):
    template_name = "base/message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.GET.get("title", "You Got the Following Messages")
        return context

src/apps/base/views/client.py
from django.views.generic import TemplateView


class ClientView(TemplateView):
    template_name = "index.html"

src/apps/base/views/get_started.py
from django import forms
from django.shortcuts import render
from django.utils.translation import gettext as _
from formtools.wizard.views import SessionWizardView

from apps.base.constants import IS_LANGUAGES_SELECTED, PRIMARY_LANGUAGE, SECONDARY_LANGUAGE
from apps.base.utils.decorators import form_helper
from apps.base.utils.languages import get_language_choices, get_level_choices, set_language_preferences


@form_helper
class PageOneForm(forms.Form):
    primary_language = forms.ChoiceField(
        choices=get_language_choices().get(PRIMARY_LANGUAGE, None),
        label=_("Language to learn"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageTwoForm(forms.Form):
    secondary_language = forms.ChoiceField(
        choices=get_language_choices().get(SECONDARY_LANGUAGE, None),
        label=_("Secondary language"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageThreeForm(forms.Form):
    level = forms.ChoiceField(
        choices=get_level_choices(),
        label=_("Difficulty Level"),
        widget=forms.RadioSelect(),
    )


class GetStartedWizard(SessionWizardView):
    form_list = [PageOneForm, PageTwoForm, PageThreeForm]
    template_name = "base/get-started.html"

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        all_data = {}
        for step in self.get_form_list():
            cleaned_data = self.get_cleaned_data_for_step(step) or {}
            all_data.update(cleaned_data)
        context["all_data"] = all_data
        return context

    def done(self, form_list, **kwargs):
        data = {}
        for form in form_list:
            data.update(form.cleaned_data)

        response = render(self.request, "base/welcome.html", {IS_LANGUAGES_SELECTED: True})
        set_language_preferences(response=response, data=data)

        return response

src/apps/base/views/languages.py
from django.shortcuts import render
from django.views import View

from apps.base.constants import IS_LANGUAGES_SELECTED
from apps.base.forms import LanguagePreferencesForm
from apps.base.utils.languages import get_language_preferences, set_language_preferences


class LanguagePreferencesView(View):
    template_name = "base/components/update.html"
    form_class = LanguagePreferencesForm

    def get(self, request, *args, **kwargs):
        initial_data = get_language_preferences(request=request)
        form = self.form_class(initial=initial_data)
        context = {
            "form": form,
            "action_url_name": "base:language_preferences",
            "title": "Language Preferences",
            "button_color": "btn-success",
            "button_text": "Submit",
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            context = {IS_LANGUAGES_SELECTED: True}
            response = render(request, "base/welcome.html", context)
            cleaned_data = form.cleaned_data
            set_language_preferences(response=response, data=cleaned_data)
            return response

src/apps/base/views/mpview.py
from django import forms
from django.shortcuts import render
from django.utils.translation import gettext as _
from formtools.wizard.views import SessionWizardView

from apps.base.constants import PRIMARY_LANGUAGE, SELECTED_LANGUAGE
from apps.base.utils.decorators import form_helper
from apps.base.utils.languages import get_language_choices, get_level_choices


@form_helper
class PageOneForm(forms.Form):
    selected_language = forms.ChoiceField(
        choices=get_language_choices().get(SELECTED_LANGUAGE, None),
        label=_("Language to learn"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageTwoForm(forms.Form):
    primary_language = forms.ChoiceField(
        choices=get_language_choices().get(PRIMARY_LANGUAGE, None),
        label=_("Secondary language"),
        widget=forms.RadioSelect(),
    )


@form_helper
class PageThreeForm(forms.Form):
    level = forms.ChoiceField(
        choices=get_level_choices(),
        label=_("Difficulty Level"),
        widget=forms.RadioSelect(),
    )


class MyFormWizard(SessionWizardView):
    form_list = [PageOneForm, PageTwoForm, PageThreeForm]
    template_name = "base/preferences.html"

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        all_data = {}
        for step in self.get_form_list():
            cleaned_data = self.get_cleaned_data_for_step(step) or {}
            all_data.update(cleaned_data)
        context["all_data"] = all_data
        return context

    def done(self, form_list, **kwargs):
        data = {}
        for form in form_list:
            data.update(form.cleaned_data)

        response = render(self.request, "base/welcome.html", {"form_data": data})
        for key, value in data.items():
            response.set_cookie(key, value)

        return response

src/apps/base/templates/base/components/fonts.html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Style+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

src/apps/base/templates/base/components/form.html
{% load i18n %}

{% load crispy_forms_tags %}

<form method="post" action="{{ action_url }}">
  {% csrf_token %}
  <div>{{ form|crispy }}</div>

  {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}

  <div class="d-flex btn-group pt-1">
    <button type="submit" class="btn {{ button_color }}">{% trans button_text %}</button>
  </div>
</form>

src/apps/base/templates/base/components/icons.html
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

src/apps/base/templates/base/components/navbar.html
{% load static %}

{% load i18n %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light shadow">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'base:client' %}">
      <img src="{% static 'base/images/favicon/android-chrome-512x512.png' %}" alt="brand-logo" height="24" class="d-inline-block align-text-top">
      {{ brand_name }}
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!--
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if is_languages_selected %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cards:first' %}">
              <i class="fa-solid fa-file me-2"></i>{% trans "Flashcard" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'words:list' %}">
              <i class="fa-regular fa-file-word me-2"></i>{% trans "Words" %}
            </a>
          </li>
        {% endif %}
      </ul>

      {% if is_languages_selected %}
        <hr class="d-lg-none">
      {% endif %}

      -->

      <ul class="navbar-nav ml-auto">

        <!--
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:language_preferences' %}">
            <i class="fa-solid fa-gear me-2"></i>{% trans "Language Preferences" %}
          </a>
        </li>
        -->


        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
               aria-expanded="false">
              <i class="fa-regular fa-id-card me-2"></i>{% trans "Account" %}
            </a>
            <ul class="dropdown-menu dropdown-menu-end width-auto" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item text-nowrap" href="{% url 'users:profile' slug=request.user.username %}">
                  <i class="fa-solid fa-user me-2"></i>{% trans "Profile" %}
                </a>
              </li>
              <li>
                <a class="dropdown-item text-nowrap" href="{% url 'account_logout' %}">
                  <i class="fa-solid fa-up-right-from-square me-2"></i>{% trans "Log Out" %}
                </a>
              </li>
            </ul>
          </li>

        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">
              <i class="fa-solid fa-user-plus me-2"></i>{% trans "Sign Up" %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">
              <i class="fa-solid fa-right-to-bracket me-2"></i>{% trans "Log In" %}
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

src/apps/base/templates/base/components/open-graph.html
{% load static %}

<meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{% url 'base:home' %}">
<meta property="og:type" content="website">
<meta property="og:title" content="German Vocabulary">
<meta property="og:description" content="A simple and easy way to learn German vocabulary.">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'base/images/global/open-graph.jpeg' %}">

<meta name="twitter:card" content="{{ request.scheme }}://{{ request.get_host }}{% static 'base/images/global/open-graph.jpeg' %}">
<meta property="twitter:domain" content="{{ request.get_host }}">
<meta property="twitter:url" content="{{ request.scheme }}://{{ request.get_host }}{% url 'base:home' %}">
<meta name="twitter:title" content="German Vocabulary">
<meta name="twitter:description" content="A simple and easy way to learn German vocabulary.">
<meta name="twitter:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'base/images/global/open-graph.jpeg' %}">

src/apps/base/templates/base/components/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'base/styles/base.css' %}">
<link rel="stylesheet" href="{% static 'users/styles/profile.css' %}">
<link rel="stylesheet" href="{% static 'cards/styles/base.css' %}">
<link rel="stylesheet" href="{% static 'cards/styles/messages.css' %}">
<link rel="stylesheet" href="{% static 'words/styles/base.css' %}">

src/apps/base/templates/base/components/update.html
{% extends "base.html" %}
{% load i18n %}

{% block main_content %}
  {% url action_url_name as action_url %}
  <div class="container d-flex justify-content-center pt-4 pb-4">
    <div class="card shadow profile pt-4 pb-2">
      <div class="card-body">
        <h5 class="card-title text-center">{% trans title %}</h5>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            {% include "base/components/form.html" %}
          </li>
        </ul>
      </div>
    </div>
  </div>
{% endblock main_content %}